apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dispatcher
  namespace: default
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dispatcher
  namespace: default
subjects:
- kind: ServiceAccount
  name: dispatcher
  namespace: default
roleRef:
  kind: Role
  name: dispatcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dispatcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dispatcher
    spec:
      serviceAccountName: dispatcher
      containers:
      - name: dispatcher
        image: ghcr.io/mikouaj/dispatcher:latest
        env:
        - name: DISPATCHER_LOG_FORMAT
          value: JSON
        - name: COMPRESSOR_IMAGE
          value: ghcr.io/mikouaj/compressor:latest
        envFrom:
        - configMapRef:
            name: dispatcher-config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
